package:
  name: rg_spdlog
  version: "0.16.3"

source:
  fn: v0.16.3.tar.gz
  url: https://github.com/gabime/spdlog/archive/v0.16.3.tar.gz
  md5: c4c56f986aa985677ca1db89630a2e11

build:
  number: 1
  string: gcc5

requirements:
   build:
    - cmake 3.3.1
    - rg_gcc 5.4.0
   run:
    - rg_gcc >=5.4.0

about:
  home: https://github.com/gabime/spdlog
  license: FREE 
  summary: Super Fast C++ logging library
