package:
  name: rg_gcc
  version: "7.1.0"

source:
  fn: gcc-7.1.0.tar.bz2
  url: http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-7.1.0/gcc-7.1.0.tar.bz2
  md5: 6bf56a2bca9dac9dbbf8e8d1036964a8

build:
  detect_binary_files_with_prefix: False # [not linux32]
  number: 1
  string: v1

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
