package:
  name: rg_boost.ubuntu
  version: "1.67.0"

build:
  number: 1
  string: gcc55

source:
  url: https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
  sha256: 2684c972994ee57fc5632e03bf044746f6eb45d4920c343937a465fd67a5adba

requirements:
  build:
    - rg_python_base.ubuntu 3.6.3 gcc55
    - rg_gcc =5.5
    #- icu               [unix]
    #- bzip2             [unix]
    #- zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - rg_python_base.ubuntu 3.6.3 gcc55
    - rg_gcc >=5.5
    #- icu               [unix]
    #- zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

