package:
  name: rg_doxygen
  version: "1.8.14"

build:
   number: 1
   string: v1

source:
  url: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.src.tar.gz
  md5: 41d8821133e8d8104280030553e2b42b

requirements:
  build:
    - cmake 3.3.1

about:
  home: http://www.stack.nl/~dimitri/doxygen/
  license: GPL
