package:
  name: rg_libevent
  version: "2.0.22"

source:
  url: https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
  md5: c4c56f986aa985677ca1db89630a2e11

build:
  number: 1
  string: gcc55

requirements:
   build:
    -  rg_gcc =5.5
   run:
    -  rg_gcc >=5.5

about:
  home: http://libevent.org/
  license: BSD 
  summary: an event notification library
