package:
  name: rg_memcached
  version: "1.5.7"

source:
  url: https://memcached.org/files/memcached-1.5.7.tar.gz
  sha1: 31d6f6b80668025e4616aa2ad5c7a45f24ed9665

requirements:
  build:
    - rg_gcc =5.5
    - rg_libevent 2.0.22 gcc55
  
  run:
    - rg_libevent 2.0.22 gcc55
    - rg_gcc >=5.5

build:
  number: 1
  string: gcc55

about:
  home: https://memcached.org
  license: BSD
  summary: Free & open source, high-performance, distributed memory object caching system
