package:
  name: rg_mpfr
  version: "4.0.1"

build:
  number: 1
  string: v1

source:
  url: http://www.mpfr.org/mpfr-current/mpfr-4.0.1.tar.bz2
  md5: 8c21d8ac7460493b2b9f3ef3cc610454

requirements:
  build:
    - rg_gmp 6.1.2 v1
  run:
    - rg_gmp 6.1.2 v1

test:
  files:
    - test.c

about:
  home: http://www.mpfr.org/
  license: LGPL
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.
