package:
  name: rg_python.ubuntu
  version: "3.6.3"

build:
  number: 1
  string: gcc5

source:
  path: .

requirements:
  build:
    - rg_python_base.ubuntu 3.6.3 gcc5
  run:
    - rg_python_base.ubuntu 3.6.3 gcc5
test:
  imports:
    - jinja2
    - arrow
    - paramiko
    - gevent
    - greenlet
    - requests
  commands:
    - bumpversion -h               [unix]


about:
  home: http://www.python.org/
  license: PSF
  summary: general purpose programming language
