package:
  name: rg_python_base.ubuntu
  version: "2.7.14"

source:
  url: https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
  md5: 1f6db41ad91d9eb0a6f0c769b8613c5b

requirements:
  build:
    - rg_patchelf >=0.8
    - rg_gcc =5.5
  run:
    - rg_gcc >=5.5

build:
  no_link: bin/python
  number: 1
  string: gcc55

test:
  commands:
    - python -V               [unix]

about:
  home: http://www.python.org/
  license: PSF
  summary: general purpose programming language
