package:
  name: rg_python.ubuntu
  version: "2.7.14"

build:
  number: 1
  string: gcc55

source:
  path: .

requirements:
  build:
    - rg_python_base.ubuntu 2.7.14 gcc55
  run:
    - rg_python_base.ubuntu 2.7.14 gcc55
test:
  imports:
    - jinja2
    - arrow
    - paramiko
    - gevent
    - greenlet
    - requests
  commands:
    - scons --version              [unix]
    - bumpversion -h               [unix]


about:
  home: http://www.python.org/
  license: PSF
  summary: general purpose programming language
