package:
  name: rg_mpc
  version: "1.1.0"

build:
   number: 1
   string: v1

source:
  url: https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
  sha1: b019d9e1d27ec5fb99497159d43a3164995de2d0

requirements:
  build:
    - rg_gmp 6.1.2 v1
    - rg_mpfr 4.0.1 v1
  run:
    - rg_gmp 6.1.2 v1
    - rg_mpfr 4.0.1 v1

about:
  home: http://www.multiprecision.org/
  license: GPL
  summary: Gnu Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
