package:
  name: rg_gcc
  version: "8.2.0"

source:
  # specify one or more url, or git,svn,hg or local paths
  - url: http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-8.2.0/gcc-8.2.0.tar.gz
    folder: gcc
    md5: ee04f0c22a941f5f17d93809387f2729
  - url: http://ftp.gnu.org/gnu/binutils/binutils-2.31.tar.gz
    folder: binutils
    md5: a332503c7f72ad02f4ef624fac34c4af
  #- git_url: https://github.com/ilanschnell/bsdiff4.git
  #  git_rev: 1.1.4
  #- hg_url: ssh://hg@bitbucket.org/ilanschnell/bsdiff4
  #  hg_tag: 1.1.4
  #- svn_url: https://github.com/ilanschnell/bsdiff
  #  svn_rev: 1.1.4
  #  svn_ignore_externals: True # (defaults to False)
  #- path: ../src

build:
  detect_binary_files_with_prefix: False # [not linux32]
  number: 1
  string: v1 # by default the build string will be the conda-build string.
  # script: <script_name>.sh <args> to execute instead of running build.sh
  # rpaths: # use the following rpaths in executables
  #  - lib/
  #  - lib64/
  #  always_include_files: # include files which are already in the bin folder (from dependencies)
  #     - bin/file1
  #     - bin/file2

requirements:
    build:
      - rg_gmp 6.1.2 v1
      - rg_mpfr 4.0.1 v1
      - rg_mpc 1.1.0 v1
      - rg_isl 0.19 v1
    run:
      - rg_gmp 6.1.2 v1
      - rg_mpfr 4.0.1 v1
      - rg_mpc 1.1.0 v1
      - rg_isl 0.19 v1

test:
  commands:
    - g++ --version
    - ld --version

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
