package:
  name: rg_protobuf
  version: "3.5.1"

build:
   number: 1
   string: gcc55

source:
  url: https://github.com/google/protobuf/archive/v3.5.1.tar.gz
  md5: 710f1a75983092c9b45ecef207236104

requirements:
  build:
    - cmake 3.3.1
    - rg_gcc =5.5
  run:
    - rg_gcc >=5.5

about:
  home: https://github.com/google/protobuf
  license: Google Inc.
  summary: Protocol Buffers (a.k.a., protobuf) are Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data.
